### ISSUE TITLE
Организовать логирование через log4net

### ISSUE THREAD

**Issue by KP0H** [KpdApps/Orationi.Messaging#16]
Подключить log4net, настроить логирование для всех проектов.
Заменить все выводы в консоль на log4net (возможно дублировать вывод в консоль, но средствами библиотеки)

**Comment by Berad** [comment]
Мне тут поцаны ссылок кинули в помощь.
Сохраню

https://stackify.com/making-log4net-net-core-work/
https://stackoverflow.com/questions/46169606/how-to-use-log4net-in-asp-net-core-2-0
https://habrahabr.ru/post/310770/

**Comment by Berad** [comment]
It's alive.
Now in ServerCore need to change Console.WriteLine-s to Log.LogInformation()
